import com.tw.Application;
import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'zyang' at '3/23/16 3:13 PM' with Gradle 2.7
 *
 * @author zyang, @date 3/23/16 3:13 PM
 */
public class ApplicationTest {
    @Test public void testSomeLibraryMethod() {
    }
}
